### ISSUE TITLE
Revise which fields should be audited when hidden

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#30]
Hidden form fields should not fail some audits. Example: **Help your users using alternate input methods complete this form by ensuring each field is correctly labeled**

Hovering over the item results in the following error

> ```
> Error in event handler: Error: Failed to execute 'querySelectorAll' on 'Document': 'html > body > div:nth-of-type(1) > div > div > main > div:nth-of-type(1) > form > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(2) > div > div > input[-1]' is not a valid selector.
> ```

`-1` should never be included in the css selector.

**To Reproduce** Steps to reproduce the behavior:

1. Visit: https://partakefoods.com/
2. Add an item to the cart
3. Proceed to checkout
4. Open the developer console
5. Launch the extension
6. Click on one of the issues (e.g. `<input autocomplete="shipping given-name" class="visually-hidden" name="checkout[shipping_address][first_name]" type="text" ...>`)
5. See error

**Expected behavior** A clear and concise description of what you expected to happen.

Hidden fields should not be audited, and CSS selector should never return `-1`;

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/2647062/128555813-e0517162-7f31-4e3c-9fe7-b5d5db1b8e4e.png)

**Comment by socsieng** [comment]
Turns out that the `.visually-hidden` fields are still technically visible according to:

```ts
function isElementVisible(elem: ChildNode): boolean {
  if (elem instanceof HTMLElement) {
    return !!(elem.offsetParent || elem.offsetWidth || elem.offsetHeight || elem.getClientRects?.().length);
  }
  return true;
}
```

The fields is hidden using `clip`:

```css
.visually-hidden {
  border: 0;
  clip: rect(0, 0, 0, 0);
  clip: rect(0 0 0 0);
  width: 2px;
  height: 2px;
  margin: -2px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  white-space: nowrap;
}
```

Checking for this type of visibility may be an expensive operation so it might be best to ignore this for now.
